### ISSUE TITLE
can we have it for ios also ?

### ISSUE THREAD

**Issue by ronak301** [luggg/react-native-android-snackbar#17]

**Comment by DeDuckProject** [comment]
I also couldn't find anything similar to both iOs and Android..
Closest thing is toast..
https://github.com/remobile/react-native-toast
Exists here but cannot make them responsive...

**Comment by pedro** [comment]
Hey folks!

I'm not planning to add iOS support because Apple users are probably not familiar/not expecting Snackbars in iOS apps. Apple has their [own interface guidelines](https://developer.apple.com/ios/human-interface-guidelines/), I think among these [alerts](https://developer.apple.com/ios/human-interface-guidelines/ui-views/alerts/) are the closest to a snackbar.

That said there is at least [one open source implementation of Snackbar for iOS](https://github.com/stonesam92/SSSnackbar), so anyone interested could see about adapting that to work with RN!
