### ISSUE TITLE
Snackbar overlap with system menu on Android 5.0 Lollipop

### ISSUE THREAD

**Issue by pewh** [luggg/react-native-android-snackbar#8]
I think we need recalculate Snackbar bottom position on Android 5.0 Lollipop. I **cannot** click DISMISS button anymore if overlap like that.

Before trigger Snackbar:
![screenshot_20160515_094525](https://cloud.githubusercontent.com/assets/881358/15271732/28f8e358-1a82-11e6-9ac3-1c2a1d5706b6.png)

After trigger Snackbar:
![screenshot_20160515_094542](https://cloud.githubusercontent.com/assets/881358/15271733/2fa9a372-1a82-11e6-8000-cb47f8fd8a1e.png)

PS: It has no issue on Android before Lollipop.

**Comment by duranmla** [comment]
Same happens for Android 6.0, it happens to be on my HTC_M8

**Comment by duranmla** [comment]
Ok this issue is happening because of this line https://github.com/luggg/react-native-android-snackbar/blob/master/android/src/main/java/com/lugg/ReactSnackbar/ReactSnackbarModule.java#L32 where we get the current view to display the snackbar, instead, we should use some of the approaches listed [here](http://stackoverflow.com/questions/5273436/how-to-get-activitys-content-view) or we can apply like: `View view  = activity.getCurrentFocus();` which is going to give us the content space that we need too.

I can make a PR later.

**Comment by duranmla** [comment]
This issue has been solved after the upgrade to the v0.0.5 using the code suggested on #11

**Comment by pedro** [comment]
:+1:! Thank you
